### ISSUE TITLE
Custom getters

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-connect#1096]
https://github.com/paritytech/substrate/issues/2271

Currently we are using custom RPC to implement custom getters to avoid code duplication between runtime logic and frontend.

It is an essential feature and we simply cannot convert to Substrate Connect without this feature.

No smart contract chain is able to use Substrate connect without this.

**Comment by tomaka** [comment]
If the logic is already in the runtime, then you can declare a function with `decl_runtime_apis!` that invokes this logic. This should in principle add less than a hundred bytes or so per call to the size of the Wasm.
You can then call the function [with `state_call`](https://polkadot.js.org/docs/substrate/rpc#callmethod-text-data-bytes-at-blockhash-bytes) (the current API supported by both Substrate and smoldot) or [`chainHead_unstable_call`](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_call.html) (better designed but supported only by smoldot).

I don't actually know whether PolkadotJS provides a convenient way to use `state_call`, but in case it doesn't, it's not very difficult to use. For example if you want to call [`this function`](https://github.com/paritytech/substrate/blob/0ba251c9388452c879bfcca425ada66f1f9bc802/primitives/finality-grandpa/src/lib.rs#L535), you'd call something like `state.call("GrandpaApi_current_set_id", "0x", <optional_block_hash>)`.

Calling functions that are declared in the runtime is the "correct" way to do this, rather than custom RPCs.
We have a network request specifically for these runtime calls, thanks to which a light client will download all the storage values accessed by the function call at once, whereas if you implemented the logic on the client side you might need a lot of round trips.
It also guarantees that, if there's a runtime upgrade that changes the logic, there's no mismatch between the logic in the runtime and the logic in the client.

If the runtime bloat of exposing these functions is too large (for example if the runtime never actually uses that function internally), we want to add in the future [a different way to provide custom logic](https://github.com/paritytech/json-rpc-interface-spec/issues/4) where the user of the JSON-RPC layer provides a Wasm file containing just the logic that they need.

**Comment by xlc** [comment]
ok `state_call` can solve my issue. will open issue on polkadot.js side for a convenient way to use it.

**Comment by wirednkod** [comment]
> ok `state_call` can solve my issue. will open issue on polkadot.js side for a convenient way to use it.

I think maybe [this](https://polkadot.js.org/docs/substrate/rpc/#state) is what you are searching for

**Comment by xlc** [comment]
Not exactly. Instead of calling `api.rpc.state.call("GrandpaApi_current_set_id", "0x", <optional_block_hash>)`, I would like to make it `api.call.grandpa.current_set_id(<optional_block_hash>)`

**Comment by tomaka** [comment]
I just realized that `state_call` isn't implemented in smoldot. But I think that this is just an overlook: all the code necessary to implement it is there, and I should be able to fix that quickly.

**Comment by shunjizhan** [comment]
@tomaka is there any example of `state_call` that has parameters? Let's say the parameter is an object whose shape is
```
{
  data: string,
}
```
I tried something like this but didn't seem to work, I might be encoding the params incorrectly?
```ts
const encodedCallData = SCALE-encode({ data: '0xSomeData' });
const res = api.rpc.state.call('method_name', encodedCallData);
```

the error I got is 
```
RPC-CORE: call(method: Text, data: Bytes, at?: BlockHash): Bytes:: -32000: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x9e45 - <unknown>!rust_begin_unwind
    1: 0x8f3b - <unknown>!core::panicking::panic_fmt::h1b465604beffa55a
    2: 0x472148 - <unknown>!EVMRuntimeRPCApi_call
```
