### ISSUE TITLE
Staking bags not loading

### ISSUE THREAD

**Issue by FilippoFranchini** [paritytech/substrate-connect#1140]
When I choose to connect to polkadot using light clients and substrate connect extension (showing I am connected), I am not able to load the staking bags under the staking menu in polkadot js.

On the topright header in polkadot js I can see: smoldot-light-wasm v0.6.19

Not sure what the issue is, but anything else loads quite fast, even faster than without light clients!

Cheers
Filippo

**Comment by wirednkod** [comment]
Thank you for the feedback @FilippoFranchini .
Im investigating the reason why bags won't load and will get back to you.

The minor:

> As a minor thing I noticed that the polkadot logo is missing from the header when I choose light clients.

is more for an issue to be opened in [polkadotjs apps](https://github.com/polkadot-js/apps/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) thought, rather than here

**Comment by wirednkod** [comment]
Works now in latest version of [apps under staking](https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fpolkadot#/staking)
