### ISSUE TITLE
Cannot use from within a service-worker

### ISSUE THREAD

**Issue by jeluard** [paritytech/substrate-connect#1371]
ServiceWorker allows (via [periodicSync](https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API)) to run background logic inside a browser, without an associated web context. This allows nice use cases like triggering notifications or pre-loading data even when the webapp is actually not open nor running.

This comes with some limitation though: dynamic `import`s [can't be used](https://web.dev/es-modules-in-sw/#static-imports-only) inside Service Worker.
As substrate-connect [relies on it](https://github.com/paritytech/substrate-connect/blob/main/packages/connect/src/connector/smoldot-light.ts#L23) it can't be used inside Service Worker.

Any way we could circumvent that?

**Comment by wirednkod** [comment]
Thank you @jeluard . Im not sure I understand how a service worker will resolve the issue if web app is not running (meaning the page is not open in a tab afaiu). Can you elaborate a bit more in the context of the use case?  

Once the webapp opens and connects to substrate-connect, the chains start synching from the current specs to the latest state and you can always update the database as we do in the extension, and save that content in the localstorage, in order to have the latest state of the well known chains.

**Comment by jeluard** [comment]
@wirednkod as discussed, I updated the original description. Hopefully it makes more sense now!

**Comment by jeluard** [comment]
PolkadotJS API has now been [updated](https://github.com/polkadot-js/api/pull/5405) and doesn't transitively include `substrate-connect` anymore. It would still make sense to fix this issue so that `substrate-connect` itself can be used inside ServiceWorker.

**Comment by josepot** [comment]
Hi @jeluard,

Sorry to chime in a bit late. Let me please share my thoughts on this:

Although, it is true that `substrate-connect` currently still relies on dynamic imports (which -unlike `periodicSync`- they are [an ECMAScript standard](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-import-calls), BTW). Even if that wasn't the case, you wouldn't have been able to use `substrate-connect` from a service worker for the simple reason that `smoldot` wasn't capable of running from withing a worker (among other things b/c the WebRTC API is not available from service workers).

Recently `smoldot` has made changes in its API and it's [now possible to have `smoldot` running on a `WebWorker`](https://smol-dot.github.io/smoldot/doc-javascript/#md:usage-with-a-worker). That's why I'm currently working on a new API that will allow `substrate-connect` users to benefit from that.

However, even with this new API, you will have to instantiate the provider from the main-thread, while passing to it a worker... In other words: you still won't be able to instantiate SC from a service-worker.

I must say that I'm having a *very* hard time understanding why you would need to instantiate `substrate-connect` from within a service worker, though. I don't think that makes any sense TBH. I mean, you are using the `WsProvider`, right? If so, I'm willing to bet that you are not instantiating from from withing the service-worker, right? If that's the case, then why would you want to use the `ScProvider` from a service-worker?
