### ISSUE TITLE
Huge git pack file

### ISSUE THREAD

**Issue by peetzweg** [paritytech/substrate-connect#1519]
### Issue Description

While I was cloning a pristine of this repo, I was wondering why it was 745MB big. 

```sh
du -sh substrate-connect/
745M	substrate-connect/
```

Turns out there it's mainly a packfile of the git history:
```
./.git/objects/pack/pack-dbc454c572908edc97e03a9dbf673ed8e85bf0d1.pack
```

Probably the `node_modules` where once commited to the repository and now bloating up everyone's local machine and downloading these megabytes worthlessly from remote.

Of course not a critical issue but IMHO would be worthwhile cleaning up.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Clone fresh copy of this repo
2. Check folder size:
```sh
du -sh substrate-connect/
745M	substrate-connect/
```
3. Find biggest files
```sh  
du -ah . | sort -rh | head -n 10 | sort
```

### Describe the results you received

The repo is 745mb big without any npm modules installed!

### Describe the results you expected

This repo should not be this big. It does not have a convoluted history to result in a git history this big.

### Substrate-Connect version

latest

### Provider

Other (Specify below)

### Browser version

local development

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by josepot** [comment]
> Probably the node_modules where once commited to the repository and now bloating up everyone's local machine and downloading these megabytes worthlessly from remote.

Nah... If I had to make a wild guess I would say that one of the many stale branches must be the culprit of this 🙄. I tried running `git clone git@github.com:paritytech/substrate-connect.git --single-branch` and the resulting folder is 88M. So, I will start removing stale branches.

I really hope that's the case, because otherwise we would have to re-write the history of the main branch in order to address this, and I wouldn't want to do that...
