### ISSUE TITLE
support custom parachain network

### ISSUE THREAD

**Issue by brenzi** [paritytech/substrate-connect#1520]
1. is it currently possible to support parachains?
2. is there a tutorial on how to apply the necessary changes to a fork of this repo?

**Comment by peetzweg** [comment]
Afaik the light client used in substrate connect, [smoldot](https://github.com/paritytech/smoldot), only supports relay chains like polkadot, kusama and the testnet relay chains.
However, that is not too limiting as the parachain data can still be fetched via rpc and validated against relay chain state. 

The folks from Novasama use smoldot in [Spektr](https://novaspektr.io/) and have a proper write up how they do the parachain data verification:

https://github.com/novasamatech/omni-research-docs/blob/main/parachain-data-verification/parachain-data-verification.md

**Comment by wirednkod** [comment]
@brenzi can you please elaborate on the 2nd part of your question?

**Comment by brenzi** [comment]
> @brenzi can you please elaborate a bit more on your 2nd question?

You might have answered it: I'd like to fork this repo and build an extension for a particular parachain. I was asking for instructions how to do that, where to provide the chainspec

**Comment by wirednkod** [comment]
In the [docs of substrate connect](https://docs.substrate.io/learn/light-clients-in-substrate-connect/) on the substrate.io page is explained thoroughly the steps you need to go, in order to support a parachain; 

I do not really think that you need to fork this repo for supporting a parachain - just make sure that you provide the correct spec is more than enough (especially for a parachain);

I will close this issue ticket here - as I believe that all the questions are answered; If there is extra need of support - please do not hesitate to reopen - or create a new one
