### ISSUE TITLE
Multiple Network app is not working when deployed on ghpages and/or ipfs

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#222]
Error:

index.js:375 WebSocket connection to 'ws://127.0.0.1:9944/' failed: 
    connect @ index.js:375
    connectWithRetry @ index.js:402
    .........
logger.js:58 2021-04-13 09:26:53          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure

**Comment by raoulmillais** [comment]
This is because it requires the extension to be installed. I think we need to add something like `detector.hasExtension()` to check for it so we can display a message and a call to action to install it if it's not installed

**Comment by wirednkod** [comment]
Tested with and without extension. Both cases return the same issue above. Some times when extension was activ e the following error was printed in console:
```
Uncaught SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.<anonymous> (ExtensionProvider.js:43)
    at ExtensionProvider.js:141
    ```

**Comment by raoulmillais** [comment]
That error with the extension looks like it's caused by https://github.com/paritytech/substrate-connect/issues/213

**Comment by wirednkod** [comment]
> That error with the extension looks like it's caused by #213

Not sure about that - Burnr wallet (with minor bug) and smoldot demo at the moment works with and without the extension.

**Comment by raoulmillais** [comment]
The stack trace shows an error in the extension provider trying to parse a string beginning with the letter "A" so I'm 99% sure it is caused by that issue.

The reason the multiple network demo can not work without the extension on gh-pages is because it is served on HTTPS and it connects to kusama and polkadot which do not have bootnodes with a TLS certificate. It is the only demo that does that.

I'm a little surprised you've *never* seen it work on gh-pages with the extension though. I would expect it to work if you reload the extension first then reload the page (to ensure you don't encounter #213)

**Comment by wirednkod** [comment]
Based on latest deployment this seems to work. Will close for now.

**Comment by raoulmillais** [comment]
Oh sorry I tested this this morning and thought I'd already closed it :man_facepalming: sorry

**Comment by wirednkod** [comment]
> Oh sorry I tested this this morning and thought I'd already closed it  sorry

No worries. More eyes sees things clearer 😃
