### ISSUE TITLE
Review build dependencies and ordering

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#249]
It feels like we are not using yarn workspaces + scripts + typescript quite right.  We are constantly tweaking / finding issues with the build or introducing susrprising workarounds.  I've created this issue to document the issues we've run into and to catalog investigations so far. Ultimately I'd like to feel confident we have a solid repeateable and idiomatic approach and implement any necessary changes so that we can stop monkeypatching things.

### Tweaks / Issues and Surprising workarounds

* [Adding smoldot-test-utils as a workspace](https://github.com/paritytech/substrate-connect/commit/6eb4e8091f8b493c1ae40b76e365eef5e38ad8b4)
* [Having to compile protocol to get types before linting](https://github.com/paritytech/substrate-connect/commit/07ff6d6524096efc41ba19cb932b00cec612da28)

### Upstream bugs

* [Yarn doesn't add local workspace dependency if version is 'latest'](https://github.com/yarnpkg/yarn/issues/4878)
* [Typescript eslint doesn't support typescript projects](https://github.com/typescript-eslint/typescript-eslint/issues/2094)

### Research and potential solutions to investigate further

* [Start using typescipt project references](https://stackoverflow.com/a/58185075)
* Upgrade to yarn 2?
* Switch to npm workspaces?

**Comment by wirednkod** [comment]
@raoulmillais I believe we should stop using workspaces (as I think it does not fit in our needs) and split packages and projects to separate repos.

**Comment by raoulmillais** [comment]
> @raoulmillais I believe we should stop using workspaces (as I think it does not fit in our needs) and split packages and projects to separate repos.

If I want to make a change or addition to how substrate-connect communicates with the extension: I must make changes in 3 npm packages:


`@substrate/connect` <--> `@substrate/connect-protocol-extension` <--> `extension`

I want to be able to change those 3 things *atomically*.  Having them in separate repos adds a lot of administrative burden:  
* I have to open 3 separate pull requests. 
* I have to explain in the pull request about which other specific pull requests are relevant for this changeset.
* I probably have ensure the pull requests are merged and the packages published in a specific order in order for the CI to remain green.

It also adds quite a bit of cognitive for the reviewer:
* The reviewer has to keep the 3 different pull requests in mind.
* The review no longer happens in a single "view" on github.
* The reviewer cant simply checkout the changeset anymore to run the changes for themselves before reviewing.

In order to develop and test my changes, having them in separate repos and not using `npm link` also becomes a lot harder. You mentioned just copy/pasting the code of one package into the node_modules for the packages that depend on it.  That works fine when there is a simple 1-1 dependency situation, but it doesn't scale at all for more complicated dependency graphs.  Let's look at how we would develop/test the hypothetical changeset above.

We run one of the demos in dev mode to load it in localhost and we run the extension in dev mode so we can reload it in the extension manager.

The demo (doesn't matter which one) has this dependency graph:

```
Demo --> @susbtrate/connect --> @substrate/connect-extension-protocol
```

The extension has this dependency graph:

```
extension --> @substrate/connect-extension-protocol
```

I have to copy the protocol package into the `node_modules` of @substrate/connect and the extension.  The situation with the demos is worse as I'm realistically testing in all 3 (or at least I should be!) I'm going to have to copy @substrate/connect into all 3 demos and further the protocol packages too.  Now I have to have deep knowledge of the node_modules structure (This is really bad... that structure has changed at least twice in the history of npm and is completely different between yarn / yarn 2 / npm).

The other solution you suggested was to edit the `import`s in the files where these dependencies are ... again this is quite a lot of places in this scenario I've just walked through .. It will also be super easy to accidentally commit those changes ... I can definitely see myself doing that!

Workspaces are designed to "solve" this problem of keeping multiple packages synced up with each other.  The problem is I think we've being 1) doing it slightly wrong and 2) there is at least 1 bug in the yarn workspaces implementation (see the link in the bug description above).  It is that bug that caused us to have issues when we were making changes in linked workspaces in the past.

**Comment by raoulmillais** [comment]
As for the situation with whether or not we should break with the convention of using npm.  100% we should ask the wider team what they fell about it and explain why we think it's a good idea before we commit to it :smile:

**Comment by wirednkod** [comment]
As I have mentioned before - the reason why I would not use workspaces *for the specific project* is mainly cause the project/packages in the repo are not meant to be bundled as one but as separated projects.

That been said, I'll try to give a short response concerning the reasons you mention above: 
`@substrate/connect-extension-protocol` - I think its not correct to have common package for Extension and Connect. Already objected when asked back at the point of that separation. It does make sense to be separated but that should not block each other from being released - so development sequence (and merging) should be taken into account due to that separation.

Concerning the developing process -  for each project/package on the `I have to open 3 separate pull requests.`: 
Having workspaces or not - 3 separate PRs should be opened and each PR should be backward compatible (Notes of depreciation of functions etc etc). This ensures that tasks are split in smaller autonomous entities and are developed in parallel without blocking other development tasks. 

The above should be followed and all tasks should be split into packages/projects rather than one big end-to-end development task/PR. We have faced that before - tasks and issues were blocked until those changes were finalised. In addition - split of dev tasks makes review easier and faster. Reviewer can check the issue that the autonomous PR tries to solve for the specific package/project rather than having to check 1 PR that changes 30 files between different packages/projects with chain logic etc etc.

`I probably have ensure the pull requests are merged and the packages published in a specific order in order for the CI to remain green.` - thats not needed if code is ensured to be backward compatible and all PRs are small - resolving issues on the specific package/project and are open/resolved on correct sequence. Each workspace/package/PR when merged should always keep the CI green. Also PRs should have dependencies linked with each other.

Concerning documentation notices - from [yarn workspaces docs](https://classic.yarnpkg.com/en/docs/workspaces/#toc-limitations-caveats):

> The package layout will be different between your workspace and what your users will get (the workspace dependencies will be hoisted higher into the filesystem hierarchy). Making assumptions about this layout was already hazardous since the hoisting process is not standardised, so theoretically nothing new here.

> Be careful when publishing packages in a workspace. If you are preparing your next release and you decided to use a new dependency but forgot to declare it in the package.json file, your tests might still pass locally if another package already downloaded that dependency into the workspace root. However, it will be broken for consumers that pull it from a registry, since the dependency list is now incomplete so they have no way to download the new dependency. Currently there is no way to throw a warning in this scenario.

**Comment by wanderer** [comment]
Here are a couple of other things I have found while trying to redo the deps. 
After using npm instead of yarn jest tests fail with "Error: SyntaxError: Cannot use import statement outside a module" I haven't been able to track down why. Also ts-jest should be transforming the ts code then running the tests. I'm not sure why we just don't run tests on the compile ts code directly.

**Comment by raoulmillais** [comment]
I think that #336 and #335 fixes all the pain points described in this issue apart from:

> Typescript eslint doesn't support typescript projects

But this might be mitigated by (taken from #292 but not yet tried):

The typescript eslint plugin [doesn't support project references yet](https://github.com/typescript-eslint/typescript-eslint/issues/2094) but according to [this comment](https://github.com/typescript-eslint/typescript-eslint/issues/2094#issuecomment-765142357) we can use [this option](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject) as a work around.   If so we can remove the `prelint` script that builds connect-extension-protocol before linting

I'll have a go at this and removing the prelint script to see if it works.  If it does we can close this and #264 and stick with yarn workspaces for the timebeing.
