### ISSUE TITLE
Wrong message when using connect in burnr wallet

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#311]
It says "Websocket remote client" when it's actually using @substrate/connect

**Comment by wirednkod** [comment]
I am not sure that this is a bug. 
Burnr wallet is supposed to be a demo in order to show how a wallet works with smoldot  (means - solely works with smoldot - with exception of local client which can be a full node from substrate node template).

Is this something that we would like to change? 

We could always have a 2nd dropdown for the user to choose between Smodlot/Full Node but do we want a burnr wallet for both smoldot and full node? 

CC: @goldsteinsveta I think we had a similar discussion on this before

**Comment by raoulmillais** [comment]
We're going to remove all except from the smoldot connection to westend
