### ISSUE TITLE
Remove everything except smoldot connection to westend from burnr

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#312]
This might just be a text issue but it isn't clear to the user how to switch back to using @substrate/connect in the burnr wallet. See also #311

**Comment by wirednkod** [comment]
I am not sure that this is a bug.
Burnr wallet is supposed to be a demo in order to show how a wallet works with smoldot (means - solely works with smoldot - with exception of local client which can be a full node from substrate node template).

Is this something that we would like to change?

We could always have a 2nd dropdown for the user to choose between Smodlot/Full Node but do we want a burnr wallet for both smoldot and full node?

CC: @goldsteinsveta I think we had a similar discussion on this before

**Comment by goldsteinsveta** [comment]
I'd say let's keep it simple, and not overthink this now, and demo only light clients. If there'll be a context in which it is interesting to run the same UI with remote, full and light nodes, we can add this later.

**Comment by raoulmillais** [comment]
Ok updated the title as discussed.  We will remove the "local node" connection and make burnr only connect to westend with @substrate/connect.  @goldsteinsveta please add any details if you want to make some UI changes (e.g. remove the dropdown to select the connection etc)

**Comment by goldsteinsveta** [comment]
I'd keep dropdown, for example for Westend's parachains
