### ISSUE TITLE
Permission dialogue (trust check) for new, unknown incoming apps

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#358]
When an app is trying to access the extension a "trust check" must be performed against a localstorage map ( see #357 ).
Upon this check:
- if the app exists in the map then [flow](https://www.figma.com/file/iBXxXdzoLgmNS3i0ZMOee5/Flows?node-id=0%3A1) should continue
- if the app does not exist in the map then a popup dialogue requesting consent from user in order to trust or not the app. If trusted then app should be added to the map as "known app" connected to chainspec

Designs provided on #360 

_Note: Chain spec should be marked as known if at least one app that tries to connect to that chainspec has user's consent as trustful._

**Comment by tomaka** [comment]
In my opinion this should be the other way around: an application is always allowed unless it is found in a list of banned applications in local storage.

Users should be able to add an app to this banned list by clicking a button in the UI next to a running app.

Maybe the most complicated part is that we also need some UI to "unban" an app even if it is not running.

Because space in the local storage is limited and used for other purposes, we also need to limit the number of banned apps to a certain amount.

**Comment by tomaka** [comment]
I guess we can close in favor of https://github.com/paritytech/substrate-connect/issues/738
