### ISSUE TITLE
Validate what we get from local storage in burnr

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#375]
When we upgrade or change what is stored / retrieved from local storage we get strange behaviours if we don't manually clear the local storage.  This is bound to happen again in the future, so we should add a simple validation step to check that what we got back from local storage is in the expected format and clear it if it isn't.

**Comment by wirednkod** [comment]
We cannot "clear it if it isn't" the localStorage. That is due to the fact that if a potential bug "clears" the localStorage, then the account that (maybe was) in the localStorage will be burned and all funds will be lost.

We should correct the localStorage and only in the case that the account interface expected is wrong, provide the user some data or actions to clear the localStorage.

It should always be a choice of the user and not an automated (probably unexpected) action from the app.
