### ISSUE TITLE
Change Detector API to support parachains

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#441]
```javascript
import { Detector } from '@substrate/connect';

const app = new Detector('burnr-wallet');
const westend = await app.connect('westend'); // get an API instance to talk to the relay chain (optional)
const statemine = await app.connect('westend', { chainName: 'statemine', chainSpec: '<chainspec>' });
await westend.rpc.chain.subscribeNewHeads((lastHeader) => {
  console.log(lastHeader.hash);
);

// etc ...
await statemine.disconnect();
await westend.disconnect();
```

---

We should also add a helper to allow app builders to detect when the extension is installed before `connect()`ing.  This is so that they can optionally show some UI to encourage people to install the extension.

```javascript
import { Detector } from '@substrate/connect';

const app = new Detector('burnr-wallet');
if (!app.hasExtension()) {
	// Show UI to encourage installing the extension
    // or disable the app etc
}
```

**Comment by wirednkod** [comment]
I assume that by this:
```
const westend = new Detector('burnr-wallet', 'westend');
```
you meant 
```
const app = new Detector('burnr-wallet', 'westend');
```

**Comment by wirednkod** [comment]
We could preferably instead of altering the Detector to call the `connect` as is now with first parameter of relay chain, and either:
a) 2 optional string parameters of 'name of parachain', 'chainspec of parachain' (e.g. `const statemineApi = await app.connect('westend', 'statemine', '<chainspec>');` ; or   
b) 1 optional `Map<string, string>` parameter that contains as key the name of the parachain and value the stringified chainspec (e.g. `const statemineApi = await app.connect('westend', { 'statemine': '<chainspec>});` )

**Comment by raoulmillais** [comment]
I think "B" is definitely better especially since we later want to support custom relay chains and shuffling arguments around is horrible.  I'd suggest a small alteration though (don't use the chain name as the "key" in the object - this way it's more open to extension and the types are nicer):

```javascript
import { Detector } from '@substrate/connect';

const app = new Detector('burnr-wallet');
const westend = await app.connect('westend'); // get an API instance to talk to the relay chain (optional)
const statemine = await app.connect('westend', { chainName: 'statemine', chainSpec: '<chainspec>' });
await westend.rpc.chain.subscribeNewHeads((lastHeader) => {
  console.log(lastHeader.hash);
);

// etc ...
await statemine.disconnect();
await westend.disconnect();
```

**Comment by tomaka** [comment]
The app doesn't need to specify the chain spec of the relay chain when it creates a parachain, as this information is already contained in the parachain spec.

The `potentialRelayChains` parameters of smoldot isn't here because smoldot needs that information, but in order to restrict the list of chains that smoldot considers for the relay chain.
The `SmoldotProvider` should just pass for `potentialRelayChains` every single chain that has previously been created, and the extension should pass for `potentialRelayChains` every single chain that the same app has previously added.

**Comment by raoulmillais** [comment]
Is that also true for custom relay chains @tomaka ?  If we do the halfway thing of letting users connect to custom relay chains (but not through the extension), is there enough information in the parachain spec alone for smoldot to connect to the parachain?

**Comment by raoulmillais** [comment]
Based on @tomaka 's comments in chat this doesn't change anything for the `Detector` API.  I'll consolidate the comments into the ticket description at the top
