### ISSUE TITLE
Upgrade extension to manifest v3

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#549]
Based on the timeline given by Chrome concerning [Manifest V2 support timeline](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/), 2021 is the last year that new manifest v2 extensions will be accepted (starting January 17, 2022).

Thus it is probably needed to update extension to v3 

Potential blocking problems to switching to manifest v3:

* [Service workers cannot spawn workers](https://github.com/w3c/ServiceWorker/issues/1529)
* [Background script must be replaced with service worker which cannot be persistent without a hacky workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=1152255)

**Comment by tomaka** [comment]
> [Background script must be replaced with service worker which cannot be persistent without a hacky workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=1152255)

Copy-pasting below some of what I wrote down in an Element channel:


# What is possible

So what is it still possible to do in an extension?

What an extension can now do is act as a "shared programmable cache". An extension can basically intercept HTTP requests and override their responses (for example, to load the response from the browser's storage instead), and can receive messages from web pages and send back answers, and that's roughly it.
As I've explained above, once an HTTP response has been overriden, or once a message has been answered, the script that was dedicated to this specific HTTP request or message terminates.

It is still possible to run long processes. For example, an extension can start downloading data from the Internet in the background and store it, but it seems that this comes and will always come with limitations. Right now it seems that a script will always get killed after 5 minutes no matter what. 5 minutes seems long enough, but this is an implementation detail we can't rely on in the long term, and Google might decide that since they're against long-running script they would add more restrictions.

# How do we adjust substrate-connect?

Given the constraint of not having long-running scripts, it's clear that we can't run the blockchain node in the extension anymore.
This doesn't, however, make an extension completely useless.

We can redesign the extension to handle the download part of point 1. (in the list at the start of this message), and point 4.
We could maybe still handle point 3. by starting smoldot when the browser stats, and letting it sync as far as possible before it gets killed.

Points 2 and 5, however, go out of the window.
Point 2 would become obsolete if we manage to make WebRTC work, so it shouldn't be a problem.

## More details

I think that we should run an instance of smoldot in the content script of each individual web page that wants to connect to a chain.
For context, the content script is a piece of code that extensions can inject to a page. This content script is treated like a regular piece of JavaScript that the page would have loaded and can run long-running scripts.
The advantage of having a content script is that the extension is sure that its code isn't malicious: if a content script sends a message to the extension, the extension can trust this message to be honest.

This means, for example, that a smoldot instance in a content script can sync a chain, then send its sync status to the extension, which then sends it to the other content scripts.

One possibility we have could be to start one instance of smoldot in each content script and have each of these smoldot instances connect to each other as if they were part of the peer-to-peer network, and exchange "networking" messages through the extension.
Thanks to this, only one content script needs to be actually connected to a full node, and would serve the other content scripts of the other pages. If this "master content script" goes down, another one takes the relay. When a full node sends a block announce, it gets sent only to one content script, which in turns propagates it to the other content scripts.

**Comment by wirednkod** [comment]
I have already started investigating and working on a solution for this, so I might as well assign it to me

**Comment by wirednkod** [comment]
Closed by #1272 #1280 #1295
