### ISSUE TITLE
Make the Fees calculation UI smoother

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#558]
When calculating the fees the UI does not look as smooth as the rest of the app.
Maybe we can beautify this with some magic gfrom @goldsteinsveta

**Comment by goldsteinsveta** [comment]
More smoothness nits:
- Submit should be disabled on unfocus any of the inputs till fees are calculated
- Can we calculate fees for the network on the background to avoid waiting?
- I'd suggest to render "fee" and "balance after transaction", maybe with opacity:0?, so that the submit button doesn't jump
